# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

forms:
  my-organizationmy-registration:
    path: /my-organization/my-registration
    type: issue-credential
    schema_name: my-registration.my-organization
    page_title: Title for my-registration.my-organization
    title: Title for my-registration.my-organization
    template: bcgov.index.html
    description: The my-registration credential issued by my-organization
    explanation: Use the form below to issue a Credential.
    fields:
    - name: registration_date
      label: registration_date
      type: date
      required: false
    - name: entity_name
      label: entity_name
      type: text
      required: true
    - name: entity_name_effective
      label: entity_name_effective
      type: date
      required: true
    - name: entity_address
      label: Mailing Address
      type: address
      required: true
    - name: entity_status
      label: entity_status
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: entity_status_effective
      label: entity_status_effective
      type: date
      required: true
    - name: entity_type
      label: entity_type
      type: text
      required: true
    - name: registered_jurisdiction
      label: registered_jurisdiction
      type: text
      required: false
    - name: effective_date
      label: effective_date
      type: date
      required: true
    - name: expiry_date
      label: expiry_date
      type: date
      required: false
    mapping:
      attributes:
      - name: corp_num
        from: helper
        source: uuid
  my-organizationian-permit:
    path: /my-organization/my-permit
    type: issue-credential
    schema_name: my-permit.my-organization
    page_title: Title for my-permit.my-organization
    title: Title for my-permit.my-organization
    template: bcgov.index.html
    description: The my-permit credential issued by my-organization
    explanation: Use the form below to issue a Credential.
    proof_request:
      id: greenlight_registration
      connection_id: bctob
    fields:
    - name: corp_num
      label: corp_num
      type: text
      required: true
    - name: entity_name
      label: entity_name
      type: text
      required: true
    - name: permit_type
      label: permit_type
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: permit_issued_date
      label: permit_issued_date
      type: date
      required: true
    - name: permit_status
      label: permit_status
      type: select
      options:
      - todo-1
      - todo-2
      - todo-3
      required: true
    - name: effective_date
      label: effective_date
      type: date
      required: true
    mapping:
      attributes:
      - name: permit_id
        from: helper
        source: uuid

### eof ###
